config/routes.rb
Rails.application.routes.draw do

  resources :citytowns do
    resources :schools
    
  end
  
  resources :courses do
    resources :exercices
  end 
  
  resources :materials
  resources :levels
  resources :helps
  
  get 'login/student'
  get 'login/teacher'
  get 'login/team'
  get 'dashboard/index'
  root to:'home#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout "dashboard"
  
  before_action :authenticate_user!
  before_action :find_materials
  before_action :find_levels

  def index
    @materials = Material.all
    @levels = Level.all
  end


private

  #enable material
  def find_materials
    @materials = Material.all
  end

  #enable level
  def find_levels
    @levels = Level.all
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/layouts/dashboard/_sidebar.html.erb
<nav class="w-24 flex flex-col bg-blue-500 hover:text-blue-500 ">
    <!-- Left side NavBar -->
    <div class="">
      <!-- App Logo -->
     	<%= link_to root_path, class:"flex flex-col items-center" do %>
        	<span class="font-bold text-black hover:no-underline ">LNCLASS</span>

     	<% end %>
    </div>

    <!-- teacher sidebar content-->
	<% if current_user.role == "teacher" %>

	    <span class="mt-2  capitalize">
		    <ul class="mt-3 p-2  rounded-lg">
			    <%= link_to  new_course_path, class:"flex items-center" do %>
				<span class="font-semibold text-black"> Resumé</span>
				<% end %>
            </ul>
		
		<ul class="mt-3 p-2 text-black rounded-lg">
            <%= link_to new_level_path, class:"flex items-center" do %>
                
               <span class="font-semibold text-black">Voir Resumés</span>
            <% end %>
		</ul>
		<ul class="mt-3 p-2 text-black rounded-lg">
            <%= link_to new_material_path, class:"flex  items-center" do %>
                <span class="font-semibold text-black"> Execices</span>
            <% end %>
		</ul>
		<ul class="mt-3 p-2 text-black rounded-lg">
            <%= link_to new_material_path, class:"flex  items-center" do %>
                <span class="font-semibold text-black"> Voir Execices</span>
            <% end %>
		</ul>
	</span>

    <!-- team sidebar content-->
	<% elsif current_user.role == "team" %>
    	<ul class="mt-2 text-gray-700 dark:text-gray-400 capitalize">
			<!-- Links -->
			<li class="mt-3 p-2 text-blue-600 dark:text-blue-300 rounded-lg">
				<%= link_to  root_path, class:" flex flex-col items-center" do %>
					<span class="text-xs mt-2"> Tableau de Bord</span>
				<% end %>
			</li>
			<li class="mt-3 p-2 text-dark dark-hover:text-blue-300 rounded-lg">
			    <%= link_to  new_citytown_path, class:"flex flex-col items-center" do %>
					<svg class="fill-current h-5 w-5" viewBox="0 0 24 24">
						<path
							d="M19 19H5V8h14m0-5h-1V1h-2v2H8V1H6v2H5a2 2 0 00-2
							2v14a2 2 0 002 2h14a2 2 0 002-2V5a2 2 0 00-2-2m-2.47
							8.06L15.47 10l-4.88 4.88-2.12-2.12-1.06 1.06L10.59
							17l5.94-5.94z"></path>
					</svg>
					<span class="text-xs mt-2"> Add City</span>
				<% end %>

			</li>
            <li class="mt-3 p-2 text-dark dark-hover:text-blue-300 rounded-lg">
			    <%= link_to  new_level_path, class:"flex flex-col items-center" do %>
					<svg class="fill-current h-5 w-5" viewBox="0 0 24 24">
						<path
							d="M19 19H5V8h14m0-5h-1V1h-2v2H8V1H6v2H5a2 2 0 00-2
							2v14a2 2 0 002 2h14a2 2 0 002-2V5a2 2 0 00-2-2m-2.47
							8.06L15.47 10l-4.88 4.88-2.12-2.12-1.06 1.06L10.59
							17l5.94-5.94z"></path>
					</svg>
					<span class="text-xs mt-2"> New Level</span>
				<% end %>

			</li>
			<li
				class="mt-3 p-2 text-dark dark-hover:text-blue-300
				rounded-lg">
				<%= link_to  levels_path, class:"flex flex-col items-center" do %>
					<svg class="fill-current h-5 w-5" viewBox="0 0 24 24">
						<path
							d="M19 19H5V8h14m0-5h-1V1h-2v2H8V1H6v2H5a2 2 0 00-2
							2v14a2 2 0 002 2h14a2 2 0 002-2V5a2 2 0 00-2-2m-2.47
							8.06L15.47 10l-4.88 4.88-2.12-2.12-1.06 1.06L10.59
							17l5.94-5.94z"></path>
					</svg>
					<span class="text-xs mt-2"> List Levels</span>
				<% end %>

			</li>

			<li class="mt-3 p-2 text-black rounded-lg">
				<%= link_to new_material_path, class:"flex flex-col items-center" do %>
					<svg class="fill-current h-5 w-5" viewBox="0 0 24 24">
					<path
						d="M17 10.5V7a1 1 0 00-1-1H4a1 1 0 00-1 1v10a1 1 0
						001 1h12a1 1 0 001-1v-3.5l4 4v-11l-4 4z"></path>
					</svg>
					<span class="text-xs mt-2">New Materials</span>
				<% end %>
			</li>
			<li class="mt-3 p-2 text-black rounded-lg">
				<%= link_to materials_path, class:"flex flex-col items-center" do %>
					<svg class="fill-current h-5 w-5" viewBox="0 0 24 24">
					<path
						d="M17 10.5V7a1 1 0 00-1-1H4a1 1 0 00-1 1v10a1 1 0
						001 1h12a1 1 0 001-1v-3.5l4 4v-11l-4 4z"></path>
					</svg>
					<span class="text-xs mt-2">List Materials</span>
				<% end %>
			</li>
		</ul>
		<li class="mt-3 p-2 text-black rounded-lg">
				<%= link_to new_help_path, class:"flex flex-col items-center" do %>
					<svg class="fill-current h-5 w-5" viewBox="0 0 24 24">
					<path
						d="M17 10.5V7a1 1 0 00-1-1H4a1 1 0 00-1 1v10a1 1 0
						001 1h12a1 1 0 001-1v-3.5l4 4v-11l-4 4z"></path>
					</svg>
					<span class="text-xs mt-2">New Help topic</span>
				<% end %>
			</li>
			<li class="mt-3 p-2 text-black rounded-lg">
				<%= link_to helps_path, class:"flex flex-col items-center" do %>
					<svg class="fill-current h-5 w-5" viewBox="0 0 24 24">
					<path
						d="M17 10.5V7a1 1 0 00-1-1H4a1 1 0 00-1 1v10a1 1 0
						001 1h12a1 1 0 001-1v-3.5l4 4v-11l-4 4z"></path>
					</svg>
					<span class="text-xs mt-2">List helps topics</span>
				<% end %>
			</li>
		</ul>

	<% end %>
	<!-- sign out -->
	<div class="mt-auto flex items-center p-2 text-black-700">
	<!-- important action -->
		<%= link_to destroy_user_session_path, method: :delete do %>
			<i class="fa fa-power-off" aria-hidden="true"></i>Déconnecter
      	<% end %>
	</div>
</nav>