config/routes.rb
Rails.application.routes.draw do

  resources :citytowns do
    resources :schools
    
  end
  
  resources :courses do
    resources :exercices
  end 
  
  resources :materials
  resources :levels
  resources :helps
  
  get 'login/student'
  get 'login/teacher'
  get 'login/team'
  get 'dashboard/index'
  root to:'home#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/help.rb
class Help < ApplicationRecord
  belongs_to :material
  belongs_to :user
  has_rich_text :content

  #Avoid N+1 queries
  Help.all.with_rich_text_content # Preload the body without attachments.
  Help.all.with_rich_text_content_and_embeds # Preload both body and attachments.

  #PRESENTE
  validates :title,
            :content,
            :slug,
            :author,
            :material_id,
             presence: true
  
  ################## VALIDATES  ###############
  validates :content, length: { minimum:100 }
  #SLUG
  extend FriendlyId
    friendly_id :title, use: :slugged

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/controllers/helps_controller.rb
class HelpsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_help, only: [:show, :edit, :update, :destroy]
  before_action :find_materials
  # GET /helps
  # GET /helps.json
  def index
    @helps = Help.all
  end

  # GET /helps/1
  # GET /helps/1.json
  def show
  end

  # GET /helps/new
  def new
    @help = Help.new
  end

  # GET /helps/1/edit
  def edit
  end

  # POST /helps
  # POST /helps.json
  def create
    @help        = current_user.helps.build(help_params)
    @help.author = current_user.full_name

    respond_to do |format|
      if @help.save
        format.html { redirect_to @help, notice: 'Help was successfully created.' }
        format.json { render :show, status: :created, location: @help }
      else
        format.html { render :new }
        format.json { render json: @help.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /helps/1
  # PATCH/PUT /helps/1.json
  def update
    respond_to do |format|
      if @help.update(help_params)
        format.html { redirect_to @help, notice: 'Help was successfully updated.' }
        format.json { render :show, status: :ok, location: @help }
      else
        format.html { render :edit }
        format.json { render json: @help.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /helps/1
  # DELETE /helps/1.json
  def destroy
    @help.destroy
    respond_to do |format|
      format.html { redirect_to helps_url, notice: 'Help was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_help
      @help = Help.friendly.find(params[:id])
    end

    def find_materials
      @materials = Material.all
    end

    # Only allow a list of trusted parameters through.
    def help_params
      params.require(:help).permit(:title, :content, :author, :material_id, :user_id, :slug)
    end
end

app/helpers/helps_helper.rb
module HelpsHelper
end

app/views/helps/_form.html.erb
<%= form_with(model: help, local: true) do |f| %>
  <% if help.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(help.errors.count, "error") %> prohibited this help from being saved:</h2>

      <ul>
        <% help.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, label: 'Titre:', class: "form-control",
     placeholder:"Le titre du contenu ..." %>
  </div>

  <div class="field my-1">
    <%= f.rich_text_area :content, class: "form-control ",
     placeholder: "Saissir le contenu ..." %>
  </div>

    <div class="row my-2">
      <div class="col-5  col-md-3 col-lg-3">
        <div class="input-form">
          <span class="select">
            <%= f.select :material_id,
              @materials.map { |m| [m.title, m.id] },
              placeholder:"la matiere",
               hide_label: true, class:"bg-red-200" %>

          </span>
        </div>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit "Créer le contenu",  class: "inline-flex justify-center py-2 px-4 border 
          border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-blue-600
          hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
    </div>
<% end %>

app/views/helps/edit.html.erb
<%= content_for @title= "Modifie la docu" %>

<div class="container-fluid">
  <div class="row">
  <!-- navbar course-->
   <%= render "courses/shared/navbar" %>
  <div class="col-12 col-md-7 col-lg-7 mx-auto mt-24">
    <h2 class="text-center mb-4 font-bold text-3xl">Nouvelle Documentation :</h2>
      <div class="mx-auto">
        <%= render 'form', help: @help %> 
      </div>
    </div>
  </div>
</div>

app/views/helps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Helps</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Author</th>
      <th>Material</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @helps.each do |help| %>
      <tr>
        <td><%= help.title %></td>
        <td><%= help.content %></td>
        <td><%= help.author %></td>
        <td><%= help.material_id %></td>
        <td><%= help.user_id %></td>
        <td><%= link_to 'Show', help %></td>
        <td><%= link_to 'Edit', edit_help_path(help) %></td>
        <td><%= link_to 'Destroy', help, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Help', new_help_path %>

app/views/helps/new.html.erb
<%= content_for @title= "Ajoutez une docu" %>
<div class="container-fluid">
  <div class="row">
  <!-- navbar course-->
   <%= render "courses/shared/navbar" %>
    <div class="col-12 col-md-7 col-lg-7 mx-auto mt-24">
      <h2 class="text-center mb-4 font-bold text-3xl">Nouvelle Documentation :</h2>
      <div class="mx-auto">
        <%= render 'form', help: @help %> 
      </div>
    </div>
  </div>
</div>

app/views/helps/show.html.erb
<% content_for @title = @help.title %>

<div class="container-sm">
  <div class="row pt-16 ">
    <div class="col-12 col-md-6 col-lg-6">

      <!-- card course-->
      <div class="card">
        <!-- title!-->
        <h1 class="text-xl leading-tight font-bold mt-2 mx-2">
          <%= @help.title %>
        </h1>

         <!-- avatar data/!-->
        <div class="flex items-cente mt-4 ml-6">
          <img class="w-10 h-10 bg-gray-400 rounded-full">
          <!-- Course meta data-->
          <%= render "helps/shared/data_help" %>
        </div>

        <!--content/!-->
        <div class="m-2">
          <p class="mx-2" id="read_more">
            <%= @help.content.to_s.html_safe %>
          </p>
          <hr>
          <!-- Options-->
          <%= render "helps/shared/options" %>
        </div>
      </div>
    </div>
  </div>
</div>